#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramFormTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttestler(testler instance);
    partial void Updatetestler(testler instance);
    partial void Deletetestler(testler instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TelegramFormTest.Properties.Settings.Default.TestDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<testler> testlers
		{
			get
			{
				return this.GetTable<testler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.testler")]
	public partial class testler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sira_no;
		
		private System.Nullable<int> _test_no;
		
		private System.Nullable<int> _soru_no;
		
		private System.Nullable<int> _a;
		
		private System.Nullable<int> _b;
		
		private System.Nullable<int> _c;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<int> _e;
		
		private System.Nullable<bool> _aktif_mi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsira_noChanging(int value);
    partial void Onsira_noChanged();
    partial void Ontest_noChanging(System.Nullable<int> value);
    partial void Ontest_noChanged();
    partial void Onsoru_noChanging(System.Nullable<int> value);
    partial void Onsoru_noChanged();
    partial void OnaChanging(System.Nullable<int> value);
    partial void OnaChanged();
    partial void OnbChanging(System.Nullable<int> value);
    partial void OnbChanged();
    partial void OncChanging(System.Nullable<int> value);
    partial void OncChanged();
    partial void OndChanging(System.Nullable<int> value);
    partial void OndChanged();
    partial void OneChanging(System.Nullable<int> value);
    partial void OneChanged();
    partial void Onaktif_miChanging(System.Nullable<bool> value);
    partial void Onaktif_miChanged();
    #endregion
		
		public testler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sira_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sira_no
		{
			get
			{
				return this._sira_no;
			}
			set
			{
				if ((this._sira_no != value))
				{
					this.Onsira_noChanging(value);
					this.SendPropertyChanging();
					this._sira_no = value;
					this.SendPropertyChanged("sira_no");
					this.Onsira_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_no", DbType="Int")]
		public System.Nullable<int> test_no
		{
			get
			{
				return this._test_no;
			}
			set
			{
				if ((this._test_no != value))
				{
					this.Ontest_noChanging(value);
					this.SendPropertyChanging();
					this._test_no = value;
					this.SendPropertyChanged("test_no");
					this.Ontest_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soru_no", DbType="Int")]
		public System.Nullable<int> soru_no
		{
			get
			{
				return this._soru_no;
			}
			set
			{
				if ((this._soru_no != value))
				{
					this.Onsoru_noChanging(value);
					this.SendPropertyChanging();
					this._soru_no = value;
					this.SendPropertyChanged("soru_no");
					this.Onsoru_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a", DbType="Int")]
		public System.Nullable<int> a
		{
			get
			{
				return this._a;
			}
			set
			{
				if ((this._a != value))
				{
					this.OnaChanging(value);
					this.SendPropertyChanging();
					this._a = value;
					this.SendPropertyChanged("a");
					this.OnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b", DbType="Int")]
		public System.Nullable<int> b
		{
			get
			{
				return this._b;
			}
			set
			{
				if ((this._b != value))
				{
					this.OnbChanging(value);
					this.SendPropertyChanging();
					this._b = value;
					this.SendPropertyChanged("b");
					this.OnbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c", DbType="Int")]
		public System.Nullable<int> c
		{
			get
			{
				return this._c;
			}
			set
			{
				if ((this._c != value))
				{
					this.OncChanging(value);
					this.SendPropertyChanging();
					this._c = value;
					this.SendPropertyChanged("c");
					this.OncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this.OndChanging(value);
					this.SendPropertyChanging();
					this._d = value;
					this.SendPropertyChanged("d");
					this.OndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e", DbType="Int")]
		public System.Nullable<int> e
		{
			get
			{
				return this._e;
			}
			set
			{
				if ((this._e != value))
				{
					this.OneChanging(value);
					this.SendPropertyChanging();
					this._e = value;
					this.SendPropertyChanged("e");
					this.OneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktif_mi", DbType="Bit")]
		public System.Nullable<bool> aktif_mi
		{
			get
			{
				return this._aktif_mi;
			}
			set
			{
				if ((this._aktif_mi != value))
				{
					this.Onaktif_miChanging(value);
					this.SendPropertyChanging();
					this._aktif_mi = value;
					this.SendPropertyChanged("aktif_mi");
					this.Onaktif_miChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
